services:
  web:
    build: 
      context: .
      dockerfile: docker/php/Dockerfile
    # Remove fixed port for scaling
    # ports:
    #   - "8090:80"
    expose:
      - "80"
    volumes:
      - ./src:/var/www/html/src
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECURE=${COOKIE_SECURE}
    depends_on:
      - mongo
    restart: unless-stopped
    deploy:
      replicas: 5  # Scale web service to 5 instances

  websocket:
    build: 
      context: .
      dockerfile: docker/websocket/Dockerfile
    # Remove fixed port mapping for scaling
    # ports:
    #   - "8092:10000"  # Can't use fixed ports with multiple instances
    expose:
      - "10000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=10000
      - RUST_LOG=info
    depends_on:
      - mongo
    restart: unless-stopped
    deploy:
      replicas: 5  # This creates 5 instances

  # Load balancer to distribute traffic across websocket instances
  nginx:
    image: nginx:alpine
    ports:
      - "8090:8090"  # PHP web application
      - "8092:8092"  # WebSocket service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - websocket
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped

volumes:
  mongo_data:
