services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: notes_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:rw
    env_file:
      - ./.env
    environment:
      - PHP_MEMORY_LIMIT=256M
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: notes_mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongo_data:
