services:
  # Web Service (Apache + PHP)
  - type: web
    name: your-app-web
    env: docker
    dockerfilePath: ./docker/php/Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI
        sync: false  # You'll set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECURE
        value: "true"
      - key: DB_NAME
        value: "your_database_name"
    buildCommand: ""
    startCommand: ""

  # WebSocket Service
  - type: web
    name: your-app-websocket
    env: docker
    dockerfilePath: ./docker/websocket/Dockerfile
    plan: starter
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DB_NAME
        value: "your_database_name"
    buildCommand: ""
    startCommand: ""
